### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by cameroncrobinson** [francoisvdv/lando-mutagen#17]
```
ERROR ==> problem loading plugin lando-mutagen from /Users/user/.lando/plugins/lando-mutagen/app.js: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Mutagen.availableInProject (/Users/user/.lando/plugins/lando-mutagen/Mutagen.js:29:33)
    at module.exports (/Users/user/.lando/plugins/lando-mutagen/app.js:29:18)
    at Plugins.load (/snapshot/cli/lib/plugins.js)
    at /snapshot/cli/lib/app.js
    at tryCatcher (/snapshot/cli/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/snapshot/cli/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.<anonymous> (/snapshot/cli/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/snapshot/cli/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/snapshot/cli/node_modules/bluebird/js/release/map.js:30:10)
    at _drainQueueStep (/snapshot/cli/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/snapshot/cli/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/snapshot/cli/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate._onImmediate (/snapshot/cli/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:464:21) 
[ { service: 'cli',

```

I had been getting this error on my machine. Not too familiar with typescript, with I set a condition within the object to make sure keys isn't null in the converted js:

`const services =  () => projectConfig ? Object.keys(projectConfig.services) : 0;`

**Comment by francoisvdv** [comment]
Hi, 

I'm curious what your Lando configuration file looks like. As your temporary fix suggests, it seems the services key is missing from the project config.

Could you share your Lando file?

**Comment by francoisvdv** [comment]
Closed due to lack of response.
