### ISSUE TITLE
Error - Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mralexho** [francoisvdv/lando-mutagen#56]
Hello @francoisvdv,

I am testing out lando for a new project. Thanks for starting this project as I know how bad I/O performance can be on Macs & Windows. I've been using Mutagen w/ Docker for quite some time and it's working great.

I added your latest release [v1.0.9](https://github.com/francoisvdv/lando-mutagen/releases/tag/v1.0.9) into my ~/.lando/plugins folder, added a `.lando.mutagen.yml` file into the new project but got the following error.

```shell
lando 10:29:38 ERROR ==> problem loading plugin lando-mutagen from /Users/aho/.lando/plugins/lando-mutagen/app.js: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Mutagen.availableInProject (/Users/aho/.lando/plugins/lando-mutagen/Mutagen.js:35:33)
    at module.exports (/Users/aho/.lando/plugins/lando-mutagen/app.js:29:18)
    at Plugins.load (/snapshot/cli/lib/plugins.js)
    at /snapshot/cli/lib/app.js
    at tryCatcher (/snapshot/cli/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/snapshot/cli/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.<anonymous> (/snapshot/cli/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/snapshot/cli/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/snapshot/cli/node_modules/bluebird/js/release/map.js:30:10)
    at _drainQueueStep (/snapshot/cli/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/snapshot/cli/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/snapshot/cli/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate._onImmediate (/snapshot/cli/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:464:21)
```

Would you happen to know what's wrong? Thanks.

**Comment by francoisvdv** [comment]
Hi @mralexho 

I suspect this issue occurs in a new/fresh lando project, that does not have any services defined.

Could you share your .lando.yml file and the output from `lando config`? Knowing what `services` are defined could help me pinpoint the problem.

For now, I have added some extra checks to prevent it from erroring out in v1.0.10. Could you check if it helps?

**Comment by mralexho** [comment]
Unfortunately the file is pretty barren because it's using [Platform.sh's recipe](https://github.com/lando/platformsh). Does that help?

```shell
name: test
recipe: platformsh
config:
  id: *************
```
